# Generated by Django 4.0.4 on 2022-04-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0002_alter_inquiry_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='email_address',
            new_name='email',
        ),
    ]
